### ISSUE TITLE
Application crashes if back is pressed while image is processing

### ISSUE THREAD

**Issue by toomask** [freshdesk/mobihelp-android#18]
Steps to reproduce:
- start new conversation or open existing conversation
- select a picture to send
- press back while picture is processing ( loading spinner is visible )
- application crashes

Stack trace:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.freshdesk.mobihelp.e.b.e.a(android.graphics.Bitmap, java.lang.String)' on a null object reference
       at com.freshdesk.mobihelp.e.b.f.onPostExecute()
       at com.freshdesk.mobihelp.e.b.f.onPostExecute()
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5944)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)

**Comment by tryprasannan** [comment]
@toomask Which version of the SDK is this happening on ? I couldn't reproduce this from my end.

**Comment by toomask** [comment]
I am using v1.5.4 . 
Also created a video: https://youtu.be/JlKElfEp2T8

Stack trace:
10-02 13:33:51.934  12985-13780/? E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #4
    Process: com.example.toomas.freshdeskdemo2, PID: 12985
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A17611 from pid=12985, uid=10306 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
            at android.os.Parcel.readException(Parcel.java:1546)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
            at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
            at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
            at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
            at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
            at com.freshdesk.mobihelp.e.b.g.a(Unknown Source)
            at com.freshdesk.mobihelp.e.b.f.a(Unknown Source)
            at com.freshdesk.mobihelp.e.b.f.doInBackground(Unknown Source)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by hrishikesh-p** [comment]
We are looking into this . We will have an updated SDK for you this week
