### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by harishsquadrun** [freshdesk/mobihelp-android#21]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.freshdesk.mobihelp.b.e.b()' on a null object reference
       at com.freshdesk.mobihelp.activity.ConversationActivity.a(Unknown Source)
       at com.freshdesk.mobihelp.activity.ConversationActivity.onLoadFinished(Unknown Source)
       at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
       at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
       at android.support.v4.content.Loader.deliverResult(Loader.java:126)
       at com.freshdesk.mobihelp.d.c.b(Unknown Source)
       at com.freshdesk.mobihelp.d.c.deliverResult(Unknown Source)
       at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
       at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
       at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
       at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by shivasurya** [comment]
@tryprassana Why don't you provide source code of sdk to debug! And it seems like eclipse library project.
