### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by achinverma** [freshdesk/mobihelp-android#24]
Hi, i am facing the below issue in eclipse project , 

```
`09-13 03:12:46.862: W/System.err(5333): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/freshdesk/mobihelp/R$attr;
09-13 03:12:46.862: W/System.err(5333): 	at com.freshdesk.mobihelp.activity.BaseActionBarActivity.<clinit>(Unknown Source)
09-13 03:12:46.862: W/System.err(5333): 	at java.lang.Class.newInstance(Native Method)
09-13 03:12:46.862: W/System.err(5333): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
09-13 03:12:46.862: W/System.err(5333): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
09-13 03:12:46.862: W/System.err(5333): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-13 03:12:46.862: W/System.err(5333): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-13 03:12:46.862: W/System.err(5333): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-13 03:12:46.862: W/System.err(5333): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-13 03:12:46.862: W/System.err(5333): 	at android.os.Looper.loop(Looper.java:148)
09-13 03:12:46.862: W/System.err(5333): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-13 03:12:46.862: W/System.err(5333): 	at java.lang.reflect.Method.invoke(Native Method)
09-13 03:12:46.862: W/System.err(5333): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-13 03:12:46.862: W/System.err(5333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-13 03:12:46.863: W/System.err(5333): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.freshdesk.mobihelp.R$attr" on path: DexPathList[[zip file "/data/app/competent.groove.feetport-1/base.apk"],nativeLibraryDirectories=[/data/app/competent.groove.feetport-1/lib/arm, /data/app/competent.groove.feetport-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
09-13 03:12:46.863: W/System.err(5333): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-13 03:12:46.863: W/System.err(5333): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-13 03:12:46.863: W/System.err(5333): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-13 03:12:46.863: W/System.err(5333): 	... 13 more
09-13 03:12:46.863: W/System.err(5333): 	Suppressed: java.lang.ClassNotFoundException: com.freshdesk.mobihelp.R$attr
09-13 03:12:46.863: W/System.err(5333): 		at java.lang.Class.classForName(Native Method)
09-13 03:12:46.863: W/System.err(5333): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-13 03:12:46.863: W/System.err(5333): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-13 03:12:46.863: W/System.err(5333): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-13 03:12:46.863: W/System.err(5333): 		... 14 more
09-13 03:12:46.863: W/System.err(5333): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
`
```

**Comment by tryprasannan** [comment]
@achinverma Looks like a build issue, not being able find the R.java. Can you please perform a clean build and check ?

**Comment by achinverma** [comment]
@tryprasannan  already done **clean build**  , but still facing the issue , any-other solution ?

**Comment by achinverma** [comment]
error fixed

**Comment by niravkhunt** [comment]
but tell how you fixed that ? i am getting same error .
