### ISSUE TITLE
Failed to connect in android version 4.4

### ISSUE THREAD

**Issue by satutig** [freshdesk/mobihelp-android#26]
I am getting error failed to connect while generating ticket from android version 4.4.

**Comment by tryprasannan** [comment]
@satutig Can you please share more info of the error or the stack trace to help us understand the exact issue ?

**Note**: This product has been deprecated (as we've launched a new product replacing Mobihelp) and official support is no longer available. We'll try to help you on a best effort basis.

**Comment by satutig** [comment]
Hi , i got ssl exception  
javax.net.ssl.SSLException: Connection closed by peer
                                                                         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
                                                                         at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
                                                                         at com.android.okhttp.Connection.connect(Connection.java:107)
                                                                         at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
                                                                         at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)

**Comment by satutig** [comment]
can u please tell me, which new product you have launched? is this similar to Mobihelp, can u please share some reference URL?

**Comment by tryprasannan** [comment]
The new product is Freshchat and you can view the [new product's page here](https://www.freshworks.com/live-chat-software/)
