### ISSUE TITLE
SQLiteException on showConversations

### ISSUE THREAD

**Issue by stedi-akk** [freshdesk/mobihelp-android#9]
Got this on some devices, when trying to show conversations with Mobihelp.showConversations(context).

    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: android.database.sqlite.SQLiteException: no such table: notes (code 1): , while compiling: SELECT ticket_id, COUNT(1) FROM notes WHERE  unread = 1  GROUP BY ticket_id
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1200)
            at com.freshdesk.mobihelp.c.d.e(Unknown Source)
            at com.freshdesk.mobihelp.d.h.a(Unknown Source)
            at com.freshdesk.mobihelp.d.h.loadInBackground(Unknown Source)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)

**Comment by tryprasannan** [comment]
Can you please share the following information to allow us to check this ?
1. Mobihelp SDK Version you currently use
2. Did you upgrade mobihelp from an older version to this version and this started appearing soon after?

**Comment by stedi-akk** [comment]
1) It happens with sdk 1.3 and 1.3.1 (dont know about other versions).
2) No.

It sometimes appears on some devices, when changing MobihelpConfig. And, it may dissapear on some devices, when simply relaunch application. Also, if you clear app data (in android settings), this error will dissapear.

**Comment by tryprasannan** [comment]
@stedi-akk This is an edge case that happens only when changing app config and invokes UnreadCountAsync API from launcher activity's start. We've added a fix for this in [SDK v1.4](https://github.com/freshdesk/mobihelp-android/releases/tag/v1.4). I'm marking this issue closed. Feel free to re-open if the this surfaces again.
